# Model preset configuration
# agent_model_config:
#   designer: sflow_qwen_7B_coder_default
#   coder: sflow_qwen_7B_coder_default
#   conductor: sflow_qwen_7B_coder_default
#   api_generator: sflow_qwen_7B_coder_default
#   feature_extractor: sflow_qwen_7B_coder_default
  
agent_model_config:
  designer: deepseek_r1_default
  coder: deepseek_r1_default
  conductor: deepseek_r1_default
  api_generator: deepseek_r1_default
  feature_extractor: deepseek_r1_default
  sketch: deepseek_r1_default
  
# agent_model_config:
#   designer: deepseek_r1_precise
#   coder: deepseek_r1_precise
#   conductor: deepseek_r1_precise
#   api_generator: deepseek_r1_precise
#   feature_extractor: deepseek_r1_precise

# agent_model_config:
#   designer: gpt_5_thinking_all
#   coder: gpt_5_thinking_all
#   conductor: gpt_5_thinking_all
#   api_generator: gpt_5_thinking_all
#   feature_extractor: gpt_5_thinking_all


# agent_model_config:
#   designer: claude_sonnet_4_5_thinking_all
#   coder: claude_sonnet_4_5_thinking_all
#   conductor: claude_sonnet_4_5_thinking_all
#   api_generator: claude_sonnet_4_5_thinking_all
#   feature_extractor: claude_sonnet_4_5_thinking_all
#   sketch: deepseek_r1_default

# agent_model_config:
#   designer: gemini_3_pro
#   coder: gemini_3_pro
#   conductor: gemini_3_pro
#   api_generator: gemini_3_pro
#   feature_extractor: gemini_3_pro

# agent_model_config:
#   designer: deepseek_v3_default
#   coder: deepseek_v3_default
#   conductor: deepseek_v3_default
#   api_generator: deepseek_v3_default
#   feature_extractor: deepseek_v3_default

# agent_model_config:
#   designer: vllm_deepseek_v31_default
#   coder: vllm_deepseek_v31_default
#   conductor: vllm_deepseek_v31_default
#   api_generator: vllm_deepseek_v31_default
#   sketch: vllm_deepseek_v31_default

# Log configuration
log_dir: "/workspace/aikg_zkg/aikg_logs"

# Workflow configuration
workflow_config_path: "config/default_workflow2.yaml"

# Documentation directory configuration
docs_dir:
  designer: "resources/docs/sketch_docs"
  coder: "resources/docs/triton_docs"
  sketch: "resources/docs/sketch_docs"

# Performance analysis configuration
profile_settings:
  run_times: 50
  warmup_times: 5

# Verification configuration
verify_timeout: 300  # Timeout for verification in seconds (default 5 minutes)